[package]
name = "rust_in_synth"
version = "1.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cpal = "0.15"
crossterm = "0.27"
parking_lot = "0.12"
midir = "0.10"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "5.0"
egui = "0.28"
egui_dock = "0.13"
eframe = { version = "0.28", features = ["default"] }
dashmap = "6.1"
nih_plug = { git = "https://github.com/BillyDM/nih-plug.git", features = ["assert_process_allocs"] }
nih_plug_egui = { git = "https://github.com/BillyDM/nih-plug.git" }

[dev-dependencies]
tempfile = "3.8"
plotters = "0.3"
